Vagrant.configure("2") do |config|

  ###########################################################
  # VM n° 1 - ZEEK - Survaillance réseau
  ###########################################################
  config.vm.define "zeek" do |zeek|
    # Configuration de la box Ubuntu 20.04 Bento
    zeek.vm.box = "bento/ubuntu-20.04"

    # Configuration de la VM
    zeek.vm.provider "virtualbox" do |vb|
      vb.name = "Zeek-VM"
      vb.hostname = "vm1-zeek"
      vb.memory = "2048"  # 2GB de RAM
      vb.cpus = 2         # 2 CPUs
    end

    # Interface NAT pour le réseau public (10.0.2.x)
    zeek.vm.network "public_network", ip: "10.0.2.15", auto_config: true

    # Interface host-only pour le réseau privé (192.168.56.x)
    zeek.vm.network "private_network", ip: "192.168.56.10"
    
    # Dossier partagé monté dans /home/vagrant/shared sur la VM
    zeek.vm.synced_folder "../shared", "/home/vagrant/shared"

    # Provisioning : Configurer le système en français
    zeek.vm.provision "shell", path: "../shared/scripts/configure_locale_fr.sh"

    # Provisioning : Exécuter le script d'installation de Zeek
    zeek.vm.provision "shell", path: "scripts/install_zeek.sh"